from fastapi import FastAPI, HTTPException, Query
from src.predict import WeatherPredictor
from datetime import datetime
import os

app = FastAPI(
    title="Weather Prediction API",
    description="API for accessing 7-day weather forecasts generated by XGBoost and Random Forest models.",
    version="1.0.0"
)

# Initialize predictor
# We initialize it outside the endpoint to avoid reloading models on every request
predictor = WeatherPredictor()
try:
    predictor.load_latest_models()
except Exception as e:
    print(f"Warning: Could not load models on startup: {e}")

@app.get("/")
def read_root():
    return {
        "message": "Welcome to the Weather Prediction API",
        "endpoints": {
            "/forecast": "Get 7-day forecast. Optional param: date (YYYY-MM-DD)",
            "/health": "Check API health and model status"
        }
    }

@app.get("/health")
def health_check():
    model_count = len(predictor.models)
    return {
        "status": "healthy" if model_count > 0 else "degraded",
        "models_loaded": model_count,
        "available_models": list(predictor.models.keys()),
        "timestamp": datetime.now().isoformat()
    }

@app.get("/forecast")
def get_forecast(date: str = Query(None, description="Start date for prediction (YYYY-MM-DD)")):
    """
    Returns a 7-day weather forecast.
    If no date is provided, returns the forecast based on the latest available data.
    """
    if not predictor.models:
        # Try reloading models if none are loaded
        predictor.load_latest_models()
        if not predictor.models:
            raise HTTPException(status_code=503, detail="Models not loaded. Please train models first.")

    try:
        # Run prediction for both model types
        xgb_df = predictor.predict_7_days('xgboost', start_date=date)
        rf_df = predictor.predict_7_days('random_forest', start_date=date)

        if xgb_df.empty or rf_df.empty:
            raise HTTPException(status_code=404, detail=f"No data available to generate forecast for {date or 'latest'}")

        return {
            "start_date": xgb_df['date'].iloc[0],
            "prediction_generated_at": datetime.now().isoformat(),
            "forecasts": {
                "xgboost": xgb_df.to_dict(orient="records"),
                "random_forest": rf_df.to_dict(orient="records")
            }
        }
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"An error occurred: {str(e)}")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
